"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/P5iHLWCKU3T
 */
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ResponsiveLine } from "@nivo/line";
import { ResponsivePie } from "@nivo/pie";

export function Chart() {
  return (
    <div className="flex h-screen bg-gray-100">
      <aside className="w-64 bg-white p-5 border-r">
        <div className="mb-10">
          <div className="text-lg font-bold">Hosty.</div>
        </div>
        <nav>
          <ul>
            <li className="mb-4">
              <a className="flex items-center space-x-2 text-gray-700" href="#">
                <LayoutDashboardIcon className="w-5 h-5" />
                <span>Dashboard</span>
              </a>
            </li>
            <li className="mb-4">
              <a
                className="flex items-center space-x-2 text-gray-700 bg-gray-200 rounded-md p-2"
                href="#"
              >
                <PieChartIcon className="w-5 h-5" />
                <span>Analytics</span>
              </a>
            </li>
            <li className="mb-4">
              <a className="flex items-center space-x-2 text-gray-700" href="#">
                <LinkIcon className="w-5 h-5" />
                <span>Sites</span>
              </a>
            </li>
            <li className="mb-4">
              <a className="flex items-center space-x-2 text-gray-700" href="#">
                <ExpandIcon className="w-5 h-5" />
                <span>Explore Domain</span>
              </a>
            </li>
            <li className="mb-4">
              <a className="flex items-center space-x-2 text-gray-700" href="#">
                <FacebookIcon className="w-5 h-5" />
                <span>Website Builder</span>
              </a>
            </li>
            <li className="mb-4">
              <a className="flex items-center space-x-2 text-gray-700" href="#">
                <MenuIcon className="w-5 h-5" />
                <span>Manage Service</span>
              </a>
            </li>
            <li className="mb-4">
              <a className="flex items-center space-x-2 text-gray-700" href="#">
                <MonitorIcon className="w-5 h-5" />
                <span>Monitoring</span>
              </a>
            </li>
            <li className="mb-4">
              <a className="flex items-center space-x-2 text-gray-700" href="#">
                <ActivityIcon className="w-5 h-5" />
                <span>Activity Log</span>
              </a>
            </li>
          </ul>
        </nav>
      </aside>
      <main className="flex-1 p-5">
        <div className="flex justify-between items-center mb-10">
          <h1 className="text-xl font-semibold">Analytics</h1>
          <div className="flex space-x-4">
            <Input
              className="border rounded-md p-2"
              placeholder="Search"
              type="search"
            />
            <Avatar>
              <AvatarImage
                alt="User"
                src="/placeholder.svg?height=32&width=32"
              />
              <AvatarFallback>U</AvatarFallback>
            </Avatar>
          </div>
        </div>
        <div className="grid grid-cols-3 gap-4 mb-10">
          <Card className="bg-[#e0f4f1]">
            <CardContent>
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-3xl font-bold text-[#34d399]">45,940</h2>
                  <p className="text-sm">Redirects</p>
                </div>
                <Badge variant="secondary">+5.78%</Badge>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-[#fef3c7]">
            <CardContent>
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-3xl font-bold text-[#fbbf24]">56.1%</h2>
                  <p className="text-sm">Success rate</p>
                </div>
                <Badge variant="secondary">+3.85%</Badge>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-[#fee2e2]">
            <CardContent>
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-3xl font-bold text-[#ef4444]">3,100</h2>
                  <p className="text-sm">Errors</p>
                </div>
                <Badge variant="secondary">+1.64%</Badge>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-[#e5e7eb] col-span-3">
            <CardContent>
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-3xl font-bold text-[#6b7280]">36.2%</h2>
                  <p className="text-sm">Error ratio</p>
                </div>
                <Badge variant="secondary">-3.26%</Badge>
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-2">
            <CurvedlineChart className="w-full h-[300px]" />
          </div>
          <div>
            <LabelledpieChart className="w-full h-[300px]" />
          </div>
        </div>
      </main>
    </div>
  );
}

function LayoutDashboardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="9" x="3" y="3" rx="1" />
      <rect width="7" height="5" x="14" y="3" rx="1" />
      <rect width="7" height="9" x="14" y="12" rx="1" />
      <rect width="7" height="5" x="3" y="16" rx="1" />
    </svg>
  );
}

function PieChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
      <path d="M22 12A10 10 0 0 0 12 2v10z" />
    </svg>
  );
}

function LinkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  );
}

function ExpandIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 21-6-6m6 6v-4.8m0 4.8h-4.8" />
      <path d="M3 16.2V21m0 0h4.8M3 21l6-6" />
      <path d="M21 7.8V3m0 0h-4.8M21 3l-6 6" />
      <path d="M3 7.8V3m0 0h4.8M3 3l6 6" />
    </svg>
  );
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function MonitorIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="3" rx="2" />
      <line x1="8" x2="16" y1="21" y2="21" />
      <line x1="12" x2="12" y1="17" y2="21" />
    </svg>
  );
}

function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
    </svg>
  );
}

function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  );
}

function LabelledpieChart(props) {
  return (
    <div {...props}>
      <ResponsivePie
        data={[
          { id: "Jan", value: 111 },
          { id: "Feb", value: 157 },
          { id: "Mar", value: 129 },
          { id: "Apr", value: 150 },
          { id: "May", value: 119 },
          { id: "Jun", value: 72 },
        ]}
        sortByValue
        margin={{ top: 30, right: 50, bottom: 30, left: 50 }}
        innerRadius={0.5}
        padAngle={1}
        cornerRadius={3}
        activeOuterRadiusOffset={2}
        borderWidth={1}
        arcLinkLabelsThickness={1}
        enableArcLabels={false}
        colors={["#2563eb"]}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
        }}
        role="application"
      />
    </div>
  );
}
